#+title: The Anti-Environment Manifesto

What is the environment? The face of a virgin mountain?---that is the environment. That same mountain-face torn apart and set into the shape of a wall?---that is not the environment. What is it that separates these two forms of stone? In the case of our wall, that stone has been blasted apart, hewn into the shape of bricks, transported to the construction site, and affixed into its proper place---all by the conscious effort of man. In the case of our virgin mountainside, this has not occurred.

It is the motive power of man's mind, his destruction and reformation of what nature provides him with which is the fundamental difference between the natural and the unnatural. What, then, is it that the environmentalist advocates for? He advocates that the environment--that collection of dirt, and stone, and bugs--be protected from the gaze of man---that it be left untouched, undisturbed, by any conscious attempt to reform it into a shape which is more suitable for the attainment of the goals of thinking men.

They tell us that greed is destroying the Earth, and that greed is therefore the root of all evil. But what is the root of greed? If greed is this desire to take from nature for the betterment of man, then the root of greed is the sustenance of mankind.

They cry out that they do not wish to destroy man to aid the environment; they just want mankind to live in harmony with the environment. What, then, does it mean for mankind to live in harmony with the environment? A man fracking oil to fuel his automobile? "No!---That is destructive of the natural environment!" A man farming cows to produce milk for him to drink? "No!---That would disrupt the proper functioning of the soil!" A man mining copper to build his computers? "No!---The explosives would scare off migratory birds!" A man plucking an apple from a tree to feed his starving body? "No!---The tree needs those fruits to be eaten by grazing animals which then spread the seeds and thus continue the circle of life!"

The environmental protectionist seeks to destroy mans success and happiness here on Earth, and return him to the dirt that he has pulled himself out of. This is apocalyptic in the very core sense of that word---the defining mark of an apocalypse isn't that there was some zombie virus, or that a meteor hit, or even that people died; rather the defining characteristic behind all apocalypses is that there is a mass breakdown in the capital structure.

It is this capital structure, this collection of factors that are combined to produce further factors, eventually terminating in consumers goods, that is the mark of civilisation. Economic growth means a growth in this capital structure---it is turning away from dirty, brutal nature, towards the clean and infinite power of man. The environmentalist inversion of this is a desire that man live not by using his mind to alter his environment to be habitable for him, but rather that he live as some lower animal, fending for survival and adapting to whatever circumstances he happens to be placed in. But just as a dog cannot live as a plant would by expecting his food to come to him, so too can a man not live like a dog does, by adapting himself to his environment rather than the other way around.

We are told that there is an environmental disaster facing us---what exactly is this disasterous towards? Man, or non-man? It cannot be man, the human environment has never been better---our lives are immesurably superior to those primitives who lived every day by hunting for their food, and shivering in cold caves at night. Rather than this, the disaster is faced not by man---but by non-man. It is non-man that the environmentalist tells us that we must sacrifice for the sake of. We should not continue to conquer nature with our miraculous technology, they tell us, but rather we must restrict our growth, restrict our births, restrict our very minds.

What the environmentalist is claiming when he wishes that man stop burning his fossil fuels to stop the glaciers melting, is that those glaciers have a superior moral claim to the ice they contain than does man to his own life and wellbeing. But on what standard do they base this? The standard is certainly not the standard of a mans own life---but there exists no other possibilities. We have here a deadly package-deal:[fn:1] the environmentalist, like all altruists, preaches that sacrifice is the proper moral duty of man. They package together the fundamental questions in ethics of: (1) what are values? and (2) who should be the beneficiary of values. The altruist substitutes the second for the first---he tells us that anything is good if it is done in self-sacrifice; in the case of the environmentalist, done in sacrifice to inanimate matter. He faces here an infinite recursion: "what are values? Values are when values are provided to others."

This is the core of the environmentalist premise, it is the latest form of the bromide that man must sacrifice his own achievements---because he achieved them. It used to be that in the words of FDR, we must sacrifice for the underpriviled "one-third of a nation." Then this sacrifice was stretched to include the "underpriviled" of the entire globe. Now we are told we must sacrifice for the sake of seaweeds, bugs, and rainforests.[fn:2] The goal is always kept in mind---that man must sacrifice. It's just that now the collectivist has had to change his tactics, the attacks on the "luxuries" of modern times no longer point only at the rich allowing for the poor to be his favoured group---these luxuries extend even to the most destitute modern man. Now he must attack luxuries and claim mud and soil as his favoured group---still, he attacks the luxuries.

In the words of /The Fountainhead/'s Ellsworth Toohey: "Watch the pincer movement. If you’re sick of one version, we push you into the other. We get you coming and going. We’ve closed the doors. We’ve fixed the coin. Heads--collectivism, and tails--collectivism. Fight the doctrine which slaughters the individual with a doctrine which slaughters the individual. Give up your soul to a council--or give it up to a leader. But give it up, give it up, give it up."[fn:3]

They hate man's achievements and oppose him on the grounds that he does achieve. To concretise this, consider the following passage from the ill-named /Life/ magazine, published following massive blackouts in the Eastern United States: "It shouldn’t happen every evening, but a crisis like the lights going out has its good points. In the first place, it deflates human smugness about our miraculous technology, which, at least in the area of power distribution and control, now stands revealed as utterly flawed [...] and it is somehow delicious to contemplate the fact that all our beautiful brains and all those wonderful plans and all that marvelous equipment has combined to produce a system that is unreliable."[fn:4]

The love and pining for the environment that we often see these days has not come from nowhere---it is a symptom of just how fully man has conquered nature in modern society. Just as you might enjoy watching a horror movie from the comfort of your living room, you might enjoy going on a nature hike---because in either case you know that you are not in any real danger. Oliver Weerasinghe, UN ambassador of Sri Lanka (Ceylon), explained once that this is not a sentiment shared by all men: "The two-thirds of mankind who live in developing countries do not share the same concern for the environment as the other one-third in more affluent regions. The primary problem for these developing areas is the struggle for the bare necessities of life. It would, therefore, not be realistic to expect governments of these areas to carry out recommendations regarding environmental protection which might impede or restrict economic progress."[fn:5]

Furthermore, the so-called "natural environments" in which one is liable to hike through or camp within are often not as natural as we might think. In my country, the great forests of England were shaped by the hands of medieval loggers and the moors of the Scottish highlands were created by the most industrious of the Bronze-Age farmers. It is places such as the Darien Gap, Antarctica, and the Sahara desert that are the true representatives of nature. These locations are essentially uninhabitable by man. Even the tribesmen who live in the Amazon rainforest make clearings and burn away undergrowth---the Eskimos of northern Canada build igloos for warmth---and the men of the desert irrigate the soil with groundwater. Nowhere do you find man prosperous in some hippy "harmony with nature."

The environmental conservationists are staunch opponents of middle-class passivity---they defy conventional attitudes, clamour for action, and scream for change; all the while they are staunch proponents of a status quo with respect to the natural world. The motive is laid bare---man must sprint back into the dirt, back into the animal kingdom, back into the grave; where no production may take place.

To quote Ayn Rand: "In their cosmology, man is infinitely malleable, controllable and dispensable, nature is sacrosanct. It is only man — and his work, his achievement, his mind — that can be violated with impunity, while nature is not to be defiled by a single bridge or skyscraper. It is only human beings that they do not hesitate to murder, it is only human schools that they bomb, only human habitations that they burn, only human property that they loot — while they crawl on their bellies in homage to the reptiles of the marshlands, whom they protect from the encroachments of human airfields, and humbly seek the guidance of the stars on how to live on this incomprehensible planet."[fn:6]

The conservationists want to conserve anything--except man--and control nothing--except man.

+ turn the abstractions into concrete form
+ the sanction of the victim with respect to companies opting for environmentalism
+ "A restricted technology is a contradiction in terms"
  + "The root of production is man’s mind; the mind is an attribute of the individual and it does not work under orders, controls and compulsion, as centuries of stagnation have demonstrated. Progress cannot be planned by government, and it cannot be restricted or retarded; it can only be stopped, as every statist government has demonstrated. If we are to consider nature, what about the fact that collectivism is incompatible with man’s nature and that the first requirement of man’s mind is freedom? But observe that just as the ancient mystics of spirit regarded the mind as a faculty of divine origin and, therefore, as unnatural, so today’s mystics of muscle, observing that the mind is not possessed by animals, regard it as unnatural."
+ "There are three major reasons why you, and most people, do not protest. ... It is these three premises that you now have to check."
  1. taking technology for granted, the premise that technology is a fact of nature which will always be there
  2. Americans are naive about the nature of evil, the premise that nobody advocates man's destruction for the sake of man's destruction, or that when they say they do that they don't mean it.
  3. the education system (ran by the above people) has hampered man's ability to translate abstractions into their actual concrete forms; the premise being that it is "only theory"
+ environmentalism as a hatred of motion---the "economic stability" point brought up in Patrick's FRB space
  + nature is in a constant process of survival of the fittest; there is no static equilibrium point that nature maintains thus keeping all animals living in harmony. Every animal is constantly acting in such a way as to extinct its competition
+ noise pollution: "there is no unwanted sound in a cemetery"
+ "amidst all their appeals to nature and pleas for harmony with nature there is no discussion of man's needs and the requirements for his survival"
  + redouble the point that for man to survive he has to destroy nature---it is a zero-sum game
  + "man is treated as if he were an unnatural phenomenon"
  + man survives by production; he cannot live like a lower animal
    + the alternative premise is environmental-Marxism: on Marx all that is required to run a factory is to have access to the means of production, and mens abilities are determined by which means of production they have access to. On the environmentalist side, man can live as an animal; he has no specific nature, his nature is malleable and dependent on how exactly he is living his life.
+ life expectancy is going up in tandem with industrialisation
+ the environmentalist is not for improving man's quality of life; they attack luxuries constantly
+ "What worries ecologists is that people now upset about the environment may ultimately look to technology to solve everything..."
  + it is quite the mystery to the reasonable man why the environmentalist movement is so direly opposed to nuclear power---it is because they are against technology as such
+ In the wake of the ECP it is clear that socialism cannot allow for production, only predation. Thus they move to attack production as evil.
  + "Instead of their old promises that collectivism would create universal abundance and their denunciations of capitalism for creating poverty, they are now denouncing capitalism /for creating abundance/."
+ Rothbard pollution article: the environmentalists want the EPA rather than an adherence to property rights. This is one-half of the package deal: that pollution really is a bad thing, but they then bundle this with a "solution" of damaging man to a far greater degree.

* Footnotes

[fn:1]On this, see: Ayn Rand, introduction to /The Virtue of Selfishness/.

[fn:2]Paraphrased from Ayn Rand, "The Anti-Industrial Revolution," available at: https://courses.aynrand.org/works/the-anti-industrial-revolution/

[fn:3]Ayn Rand, /The Fountainhead/

[fn:4]CITATION NEEDED

[fn:5]Ayn Rand, "The Anti-Industrial Revolution," available at: https://courses.aynrand.org/works/the-anti-industrial-revolution/; quoting /Industry Week/, June 29, 1970

[fn:6]Ayn Rand, "The Anti-Industrial Revolution," available at: https://courses.aynrand.org/works/the-anti-industrial-revolution/
