#+title: Apollo vs Dionysus: to the Moon or the Grave

* The Archetypal Interpretation of Culture War
You are faced with a choice: you can pick either life or death, knowledge or ignorance, prosperity or apocalypse. A culture is faced with this exact same choice, but on the scale of cultures different individuals are able to take up arms on both sides of this dichotomy. This is what we call a culture war---some clash between competing tribes with different approaches to our choice. So, what then is the cause of and the true nature of a culture war? What is the essential clash that underpins the history of civilisation vs anti-civilisation? Why do some men choose to venture out to the stars, whilst others retreat into drug-induced stupor?

The answer can be found in two Greek gods---Apollo, the god of truth and light; and Dionysus, the god of wine and madness. These two fundamental archetypes can be used to explain the entire course of human history---all of the great triumphs, and all of the despicable losses; from the greatest inventors, to the lowliest bums. Every man is in some way a reflection of one or both of these two opposing forces, which I will display to you through two seemingly unrelated events---the Moon landings, and Woodstock.[fn:1]

* The Eagle has Landed
On the 16th of July 1969 the eyes of the world turned to the Kennedy Space Center, where the Apollo spacecraft was preparing to send men to the Moon. It is reported that when the shuttle landed four days later, 650 million people watched Neil Armstrong take that one small step worldwide,[fn:2] including 54 million Americans---94% of all TVs in the US were tuned in to this event.[fn:3]

The one million people who were drawn to Cape Kennedy in person were seeking out any sign of achievement in man---they came to celebrate man's capacity as a rational animal: "Those people were not a stampeding herd nor a manipulated mob; they did not wreck the Florida communities, they did not devastate the countryside, they did not throw themselves, like whining thugs, at the mercy of their victims; they did not create any victims. They came as responsible individuals able to project the reality of two or three days ahead and to provide for their own needs. There were people of every age, creed, color, educational level and economic status. They lived and slept in tents or in their cars, some of them for several days, in great discomfort and unbearable heat; they did it gamely, cheerfully, gaily; they projected a general feeling of confident goodwill, the bond of a common enthusiasm; they created a public spectacle of responsible privacy."[fn:4]

The feeling on the ground was one of genuine brotherhood---a brotherhood borne not out of mob violence or ritual filth, but out of a respect for the best in man: "It was so wonderful, people didn't want to leave after the parade had passed. They just stood there, talking about it--talking to strangers--smiling. It was so wonderful to feel, for once that people aren't vicious, that one doesn't have to suspect them, that we have something good in common."[fn:5]

Consider the immense efforts by hundreds of men that were necessary to pull such an event off---the massive chains of abstraction and deduction that must be in place before a single fleck of paint may be launched into space. Consider then the jump from this to being able to get to the Moon, and the jump from that to getting living men onto the Moon and back again. A trip to the Moon is fundamentally an expression of the fullest might of man's conceptual faculty.

* The Acid has Dropped
One month later, on the 15th of August, this would be contrasted with another sort of trip entirely---the collective acid trip that was Woodstock. 400,000[fn:6] youngsters descended upon Max Yasgur's dairy farm in Bethel, New York for a celebration of music, dance, and debauchery. The 1970 census would put this town at just 2,763 inhabitants, a number that would, over the course of a few days, balloon to rival the 1970 populations of Atlanta, GA (496,973); Cincinnati, OH (452,524); and San Jose, CA (445,779).[fn:7] The deluge of unwashed bodies immediately started setting up campsites in neighboring fields[fn:8]---apparently not thinking ahead far enough to concern themselves with where they would stay, instead opting to "go with the flow."

It is reported that "hundreds of thousands of concertgoers overwhelmed the venue's gates and jammed the roads leading to Bethel, NY. Event staff were helpless to stop unticketed attendees from walking through the venue's porous fencing. There was little event staff could do, so Woodstock became a free concert for all who could get to Yasgur's dairy farm."[fn:9]

This horde quickly overwhelmed the limited resources available to Bethel, /Newsweek/ reports that: "Festival food supplies were almost immediately exhausted [...] and water coming from wells dug into the area stopped flowing or came up impure. A heavy rain Friday night turned the amphitheater into a quagmire and the concession area into a mudhole. [...] Throngs of wet, sick and wounded hippies trekked to impromptu hospital tents suffering from colds, sore throats, broken bones, barbed-wire cuts and nail-puncture wounds. Festival doctors called it a 'health emergency,' and 50 additional doctors were flown in from New York City to meet the crisis."[fn:10]

As the rain storm hit "at least 80,000 young people sat or stood in front of the stage and shouted obscenities at the darkened skies as trash rolled down the muddy hillside with the runoff of the rain. Others took shelter in dripping tents, lean-tos, cars and trucks. [...] Many boys and girls wandered through the storm nude, red mud clinging to their bodies."[fn:11]

The zombified masses opted to aimlessly roam through fields, helping themselves to the wealth and property of the local community, as a brute incapable of conceiving second-order consequences might.[fn:12]

Richard C. Joyner, a local businessman "said that the youngsters at the festival had virtually taken over his property---camping on his lawn, making fires on his patio and using the backyard as a latrine."

"Clarence W. Townsend, who runs a 150-acre dairy farm [...] was shaken by the ordeal. 'We had thousands of cars all over our fields,' he said. 'There were kids all over the place. They made a human cesspool of our property and drove through the cornfields. There's not a fence left on the place. They just tore them up and used them for firewood."

Royden Gabriele, another farmer, explained that: "My pond is a swamp. I've got no fences and they used my field as a latrine. They picked corn and camped all over the place. They just landed wherever they could. [...] We pulled 30 of them out of the hay mow smoking pot. [...] If they come back next year I don't know what I'll do. If I can't sell, I'll just burn the place down."

Notice the trend here---it is productive men who are victimised and made to pay for the incompetence of the concert-goers.

"The three-day Woodstock fair was different from the usual pop festival from the outset. It was not just a concert but a tribal gathering, expressing all the ideas of the new generation: communal living away from the cities, getting high, digging arts, clothes and craft exhibits, and listening to the songs of revolution."[fn:13] A promoter was quoted as saying that "people will all be going into their own thing. This is not just music, but a conglomeration of everything involved in the new culture."[fn:14]

A taste of this "new culture" is given in an interview of six of the attendees:[fn:15]
#+begin_quote
Q: Did you have any idea where you'd sleep or what there would be to eat?

Judy: Well, we drove down in a caravan of two cars--there were four girls and two guys--but we were supposed to meet 20 or 30 other people who were driving down from New Hampshire and they were supposed to bring a tent, but we never met each other. We just scattered.

Q: What about food?

Judy: We brought a bag of carrots. And some soda.

Q: Did you expect to be able to buy more there?

Judy: We never really thought about it.
#+end_quote

"All the participants stressed a sense of what they called 'community'," Judy explained that: "I just had a feeling that, wow, there are so many of us, we really have power. I'd always felt like such a minority. But I thought, wow, we're a majority---it felt like that. I felt, here's the answer to anyone who calls us deviates." Indeed they were not deviating from the Dionysian culture they had been taught their entire lives---but I am getting ahead of myself. Another attendee, Steve, added that "everyone came there to be together," and what "being together" consisted of was that "everything was shared."

When asked what he wanted to be in the future, Jimmy answered that "all my life I've had just about everything I want. And I have to have whatever I want for the rest of my life, except from now on I have to begin to think of how to provide it for myself. And I don't want to work because I can't have everything and do everything I want if I have to stay in the same place from 9 to 5." When asked whether she wants a family, Judy answered: "One child. Just, you know, to procreate. But I don't want a family because I don't want to get into that much responsibility. I want to be able to move. I want to be able to leave at any time. I don't want that much restriction."

* The Essential Characteristics of Apollo and Dionysus
What we see with the Woodstock festival is in essence an expression of a concrete-bound perceptual mentality---on such a level there is only the now, no past (they do not care how the property that they pillage came into being), and no future (they do not think about where they will stay, or what they will eat when they get there). It is not coincidental that this is paired with "communal living" and a general respect for the collective over the individual---Dionysus is borne from a supposed dichotomy of reason vs emotion. The Dionysian represents "wild, primeval feelings, orgiastic joy, the dark, the savage, the unintelligible element in man---i.e. the symbol of emotion."[fn:16]

Where reason is negated and replaced with mystic whim man is left with no recourse---he grows to regard the world as mysterious and evil. His only option left is the group---for the sheep, it is other people who seem to know what they are doing... somehow; and for the shepherd, it is other people that he can control through his power of speech, reality is out of his reach.

#+begin_quote
Apollo, according to Nietzche, is a necessary element, but an unreliable and thus inferior guide to existence, that gives man a superficial view of reality: the illusion of an orderly universe. Dionysus is the free, unfettered spirit that offers man---by means of a mysterious intuition induced by wine and drugs---a more profound vision of a different kind of reality, and is thus the superior. [...] Apollo represents the principle of individuality, while Dionysus leads man "into complete self-forgetfulness" and into merging with the "Oneness" of nature.[fn:17]
#+end_quote

It is Apollo who pushes forward into unknown territory and discovers the underlying principles of whatever endeavour through the use of his reason. The mind is a faculty of the individual, just as a collective cannot digest food for you so too can a collective not think for you. There is no mystic super-reality that man gains insight into through the use of hard drugs and the "ego death" which is sought by many of these trippers---when the ego is killed the individual dies insofar as he is not sustained by some Apollonian. Just as there can be no form without matter, there can be no soul (mind) without a body---that body must be sustained through the productive efforts that are attacked and degraded by the Dionysian egregore.

If I were writing a novel and needed to find concretes for Apollonian as against Dionysian attitudes it is harder to think of two more effective events that took place at basically the same time. Despite being actual news events, the Apollo program and the Woostock festival take on that fictional characteristic that is so often elusive. This is no coincidence---wherever there is great turmoil between men there must be a fundamental conflict between competing /philosophies/.[fn:18] Apollo vs Dionysus represent the fundamental divide---between this-wordliness as against other-worldliness; between reason as valid vs reason as invalid; between the universal reign of cause and effect vs chance and contingency.

This applies also to the modern culture war---which is really another invocation of the war between Aristotle and Plato, between Rand and Kant. On the one hand we have great industrialists like Elon Musk and Jeff Bezos attempting to push man into space and conquer the stars; on the other we have their opposition made of pod people who wish for an eternal state lockdown, advocating that they be sustained not through their own productive efforts, but through stimulus cheques and universal basic income extracted from Apollo. These modern Dionysians--like all Dionysians--regard the basic root of their sustenance, Apollo, as evil and themselves as virtuous, on the grounds that he produces and they don't.

This is the inevitable implication of Altruism: it is evil and greedy for you to reap the rewards of your own production but not for others to do so /because/ you did the production---that is, if you produced something you should give it up, if you didn't produce something you should take it. So indeed, Judy was correct when she said "we're a majority [...] here's the answer to anyone who calls us deviates." Altruism is the de facto ideology of the ruling class and the hordes of their supporters. What establishment premise is it that they are supposed to be rebelling against? They agree with their professors that causality is a myth. They agree with the media that selfishness is a vice. They agree with the government that man is incompetent to plan for himself and requires a central planning bureau to provision enough supplies for him to last.

We are told by our modern Dionysian priests, the World Economic Forum, that the future is a society where you will own nothing and be happy---does this not sound like any old dirty hippy or Buddhist mystic? In classic Dionysian fashion, they forgo an explanation as to how it is that men can be happy or even reach bare sustenance without owning anything. They are marked by a rejection of cause-effect relationships as such: rejecting the root of production and happiness in a respect for property rights whilst expecting the results is merely one instantiation of this.

* The Necessary Clash Between Apollo and Dionysus
In this fight between Apollo and Dionysus, there exists those who sit on the fence, attempting to play both sides: "we can't just have pure reason," they tell us, "man needs an emotional element, and as we all know reason is completely dispassionate." This claim is fundamentally rooted in an acceptance of the Dionysian premise that there is a dichotomy between reason and emotion---this is entirely false. Emotions are not cognitive primaries, nor are they tools of cognition at all---emotions come about as a result of prior cognition performed by the individual in question. This means that there can be rational emotions, or irrational emotions.

Take as an example to highlight this the concrete case of a landlord evicting a squatter who is trespassing in his property. Two different men witness this event: an anarcho-capitalist, and a Marxist. On the one hand, the anarcho-capitalist looks upon this situation with a sense of pride and joy at the landlord's defense of his property right---he feels very positively towards what he is witnessing. On the other hand, the Marxist is distraught, he curses the landlord and wishes that the squatter would be able to continue his aggression against property that he does not own. We have here the exact same stimulus but two completely opposed emotional responses. The difference between them is derived from the different philosophies held by the anarcho-capitalist and Marxist respectively---the emotions themselves are not giving either man special information about what is happening, rather the emotional response represents the implicit evaluation of the facts based upon prior cognition.

So, far from what the Dionysians would have us believe, emotions are not mystic conduits to some ineffable spirit-dimension---they are the effects of whatever philosophy and sense of life is held by an individual. Taking one's emotions as a cognitive primary is another instance of taking an effect without consideration of the cause---as is to be expected with a Dionysian. It is the complete rejection of logic and justification in one's conduct---it is placing an "I wish" above an "it is."[fn:19]

This is evasion, it is in Rand's words:
#+begin_quote
[man’s] basic vice, the source of all his evils, [it] is that nameless act which all of you practice, but struggle never to admit: the act of blanking out, the willful suspension of one’s consciousness, the refusal to think---not blindness, but the refusal to see; not ignorance, but the refusal to know. It is the act of unfocusing your mind and inducing an inner fog to escape the responsibility of judgment---on the unstated premise that a thing will not exist if only you refuse to identify it, that A will not be A so long as you do not pronounce the verdict "It /is/." [Evasion] is an act of annihilation, a wish to negate existence, an attempt to wipe out reality. But existence exists; reality is not to be wiped out, it will merely wipe out the wiper. By refusing to say "It is," you are refusing to say "I am." By suspending your judgment, you are negating your person. When a man declares: "Who am I to know?" he is declaring: "Who am I to live?"[fn:20]
#+end_quote

This does not stand alone as a floating premise: what we have with the Dionysian on this front is a whim-epistemology---this whim-epistemology is based on the prior metaphysical premise of the primacy of consciousness. This is the stance that consciousness is the primary from which existence is derived, rather than the other way around---that if you /think/ something is the case that it therefore /is/ the case. This is a stolen concept fallacy---consciousness /means/ consciousness /of something/, of some /thing/, of /existence/. The concept "consciousness," accordingly, relies on the /prior/ concept "existence."

There is no compromise to be found here: either consciousness has metaphysical primacy or it doesn't; either reality must conform to your wishes, or it mustn't. "In any compromise between food and poison, it is only death that can win. In any compromise between good and evil, it is only evil that can profit. In that transfusion of blood which drains the good to feed the evil, the compromiser is the transmitting rubber tube."[fn:21]

The Apollo program was thus a great symbol of the power of capitalism /as against/ communism---it is not only an achievement that stands on its own grounds, but by its very greatness it is and must be a deadly weapon against the collectivist monolith to the east. In a moment of great clarity of purpose, John F. Kennedy recognised the import of such an achievement and it's mutual exclusivity with collectivism when he was pitching the idea to congress: "If we are to win the battle that is now going on around the world between freedom and tyranny [...] it is time for a great new American enterprise."[fn:22]

He recognises here first that the shining light of Apollo is a weapon in the battle between freedom and tyranny, and that this weapon must come in the form of "a great new American enterprise"---it is enterprise, i.e. production, that forms the killing blow to any self-abnegation insofar as that production is seen for what it is: brilliant.

This much was recognised, at least implicitly, by the many enemies of reason in the US. At the same time that a million people gathered to celebrate the launch of Apollo 11, a group of civil rights advocates gathered to do the exact opposite---to denounce the launch as evil and demand that the resources used to push man into the final frontier should instead "be spent to feed the hungry, clothe the naked, tend the sick, and house the shelterless."[fn:23] As their symbol, they choose to bring along two mules and a wooden wagon, displaying in great clarity the contrast between the gleaming white Saturn V rocket and the type of leech they demand it be dismantled for. The message is clear: do not advance whilst others are left behind, do not be great if others are not, do not be good if others are evil---destroy the good /for the sake of the bad/.

The activists decided that NASA should "support the movement to combat the nation's poverty, hunger and other social problems," and that the rocket scientists should be re-tasked "to tackle the problem of hunger." This notion would be redoubled by Gil Scott-Heron in his poem /Whitey on the Moon/:

#+begin_export latex
\newpage
#+end_export

#+begin_center
A rat done bit my sister Nell

With whitey on the moon

Her face and arms began to swell

And whitey's on the moon

I can't pay no doctor bills

But whitey's on the moon

Ten years from now I'll be payin' still

While whitey's on the moon
#+end_center

It is not explained by these types how it is that the "whitey on the Moon" is supposed "to tackle the problem of hunger," or what the inability of Gil to pay Nell's doctor bills has to do with him. They operate on the level of: "he'll figure it out... /somehow/." In essence, they are expecting an effect (prosperity) without the cause (the rational egoism of Apollo). It is holding up as virtuous the ones who do not produce and degrading as vicious those who do, /whilst accepting that the parasites need the producers to survive/. We have it that whitey is evil for going to the Moon whilst Gil's sister Nell is being bit by rats---whitey should not succeed whilst Nell is not. We have it that the time and resources of those NASA scientists should not be spent on the innovations they want to pursue, because other people couldn't figure out how to produce food for themselves.

This Dionysian denial of cause-effect relationships is present across the board. The Woodstock attendees who shout aimlessly at the sky to stop the rain deny that rain has a specific cause---an Apollonian would plan ahead for this eventuality, a Dionysian simply curses the incomprehensible universe when it comes along. Judy in bringing along "a bag of carrots" and "some soda" denied that hunger has a specific cause, and that this is not enough to sustain her body for the days that she would be at Woodstock. Jimmy denied the law of causality in his assertion that he doesn't want to work "because I can't have everything and do everything I want if I have to stay in the same place from 9 to 5"---but how does he expect to achieve the values he desires without producing them? The answer he blanks out is that Apollo must produce and he will suck the blood of Apollo to sustain himself.

If man is to climb the Kardashev scale and pierce the stars he simply cannot rely on Dionysian parasitism. No amount of LSD or magic mushrooms can yield an accomplishment on the scale of the Moon landings, nor on any scale---as a method of cognition they can serve only as a hindrance. Man cannot produce without freedom and Apollo cannot fly with chains.

* Socialism as Dionysian
Socialism, accordingly, is fundamentally rooted in a Dionysian philosophy. We have this on two fronts: first on the self-abnegation, the collective taken as the standard of value, the living in unity with the "Oneness" of nature leaving the individual to melt away; and second on the corollary parasitism these individuals perform against productive men.

The Dionysians seek a state of being where they live through suckling on the teat of Apollo until he is drained of life---in general any socialist scheme one dreams up requires someone to pay for it. It is the producer, Apollo, who makes the goods upon which Dionysus predates.

This socialism is present, at least implicitly, in any mass movement of Dionysians---you see it every day, whether you notice it or not. You are told that we must be tough on business---business (Apollo) is treated as the enemy which must be destroyed. You are told that there should be no such thing as billionaires---stagnation is taken as the ideal and production as a vicious divergence from it. You have seen it with the recent EU regulation of AI, along with all regulations---the Brussels bureucrats were operating on the premise that being the first to set rules on the use of AI means that they were the ones who set the stage. The stage is set by innovation, it is then attacked and warped by these busybodies and hall monitors. They are taking here a primacy of regulation, as against a primacy of production---but of course, one can only regulate an industry that was already built by Apollo. Someone had to make the AI first, and this man is being punished for his effort.

You see this same Dionysian attitude in the rejoinder to AI that it is evil because it puts men out of their jobs. Again, it is production and greater efficiency in that production which is being taken as an evil---the Dionysian expects Apollo to sustain him /somehow/, and believed that he is owed this sustenance in the form of a job regardless of how effective he actually is at that job.

* The Death of Apollo
The worst part of this is that Apollo is going along with the whole charade---he is acting as his own destroyer on this front by giving sanction to the Dionysian ticks. The first US Moon lander sent since the end of the Apollo program fell silent a week after breaking up as it touched down.[fn:24] Such accomplishments as the Apollo program cannot be achieved if sanction is granted to Dionysus---you cannot have an effect without the cause. You see this also with the AI companies who call for AI regulation, and in general, any company that calls for any regulation.

One aspect of such pleas is the corruption of previously Apollonian firms by Dionysian invaders who seek to stagnate and redirect their efforts into strangling any competition they face. Such corruption can occur within individuals as well---a man might be implicitly Apollonian but come to regard reason as helpless and integrity as impossible. This is seen most often in those who have not taken the time to iron out an explicit philosophy---if they have no explicit knowledge on such topics they have no defense-mechanism to ward off the surrounding Dionysian culture. From a single false premise in one's philosophy, whether explicit or implicit, a total destruction of their character can arise. A man might be a brilliant industrialist who applies his mind to its fullest extent in the operation of his business, but then he goes home to a family of leeches who are supported out of a sense of duty or sacrifice.[fn:25] Or a man might be perfectly wicked in his work life, taking what he can get on pragmatist grounds and cow towing to the masses to increase his pay whilst attempting to quarantine a garden of greatness within his personal dealings.[fn:26] Ultimately, such disintegrated men borne of Apollo /and/ Dionysus can find only misery.

Another aspect of these Dionysian calls for government regulation is seen in firms that are indeed Apollonian at heart but who have been infected with altruism by default, not understanding that their production is a virtue, rather than a vice. Such men are ultimately also in a state of disintegration---they understand on the one hand that they are the fountainheads of value, that they make the world go round, but then on the other hand they feed parasites who are out to kill them on the grounds that those parasites are correct. These people must understand that a world devoid of Apollo is one devoid of any productive efforts---and this is exactly what will happen if great men continue to give sanction to the bloodletting that they endure. This means nothing less than total apocalypse---an apocalypse being marked by a complete breakdown of the capital structure. This capital does not come from nowhere, it is deliberately produced by Apollonians, and it requires constant maintenance and replenishment. Sans Apollo, nature would quickly devour our cities, the lights would go out across the world and man would regress into a state of brutish savagery. This would be even worse than the state mankind was in during the stone age---at least then the trend was up, there still existed instantiations of Apollo who would invent the wheel, or fire, or spears. If such individuals no longer exist due to a victory of Dionysus, we would not have even such simple goods---we would sink back down the evolutionary ladder to a state of mere perceptual consciousness. Of course, men cannot survive on this level without rational men to sustain them---thus a victory for Dionysus means the death of mankind.

There are two fundamental and diametrically opposed choices you have here: you can choose Apollo and reach for the stars, or Dionysus and sink into the grave.

* Footnotes

[fn:1]On this, see also: Ayn Rand, "Apollo and Dionysus," in ead., /Return of the Primitive/

[fn:2]NASA, /Apollo 11 Mission Overview/, https://www.nasa.gov/history/apollo-11-mission-overview/

[fn:3]"Apollo 11 turns out as biggest show on earth," /Broadcasting/ September 1, 1969; https://www.worldradiohistory.com/Archive-BC/BC-1969/1969-09-01-BC.pdf#page=50

[fn:4]Ayn Rand, "Apollo and Dionysus," in ead., /Return of the Primitive/, p. 101

[fn:5]Ayn Rand, "Apollo and Dionysus," in ead., /Return of the Primitive/, p. 102

[fn:6]Exact attendance is unclear as many entered without tickets, 400k seems to be an accepted estimate from the time: "Peace and Sharing Dominate Festival," https://news.google.com/newspapers?id=wjkVAAAAIBAJ&pg=7277%2C284925; "'Great' rock festival ends without violence," https://news.google.com/newspapers?id=a9xVAAAAIBAJ&pg=6928%2C4284524

[fn:7]U.S. Census Bureau History: https://www.census.gov/history/www/homepage_archive/2019/august_2019.html ([[https://archive.ph/RB1XC][archived]]).

[fn:8]U.S. Census Bureau History: https://www.census.gov/history/www/homepage_archive/2019/august_2019.html ([[https://archive.ph/RB1XC][archived]]), "Days before the first performances, more than 50,000—many without tickets—set up camps in the nearby fields."

[fn:9]U.S. Census Bureau History: https://www.census.gov/history/www/homepage_archive/2019/august_2019.html ([[https://archive.ph/RB1XC][archived]]).

[fn:10]Quoted from Ayn Rand, "Apollo and Dionysus," in ead., /Return of the Primitive/, p. 109

[fn:11]Quoted from Ayn Rand, "Apollo and Dionysus," in ead., /Return of the Primitive/, p. 110

[fn:12]The following examples all come from Ayn Rand, "Apollo and Dionysus," in ead., /Return of the Primitive/, pp. 110-111

[fn:13]Quoted from Ayn Rand, "Apollo and Dionysus," in ead., /Return of the Primitive/, p. 109

[fn:14]Quoted from Ayn Rand, "Apollo and Dionysus," in ead., /Return of the Primitive/, p. 109

[fn:15]This interview is quoted from Ayn Rand, "Apollo and Dionysus," in ead., /Return of the Primitive/, pp. 112-114

[fn:16]Ayn Rand, "Apollo and Dionysus," in ead., /Return of the Primitive/, p. 100

[fn:17]Ayn Rand, "Apollo and Dionysus," in ead., /Return of the Primitive/, p. 100

[fn:18]See: Leonard Peikoff, /The Role of Philosophy and Psychology in History/, https://www.youtube.com/watch?v=PfMNCCT1uOI

[fn:19]I recall Rand saying something to this effect, but I cannot find the source.

[fn:20]Ayn Rand, "Galt's Speech" in ead., /For the New Intellectual/, p. 127; also in ead., /Atlas Shrugged/

[fn:21]Ayn Rand, "Galt's Speech" in ead., /For the New Intellectual/, p. 216; also in ead., /Atlas Shrugged/

[fn:22]Nick Spall, /How the Apollo Moon landings changed the world forever/, https://www.skyatnightmagazine.com/space-missions/how-the-apollo-moon-landings-changed-the-world-forever

[fn:23]Eric Niiler, /Why Civil Rights Activists Protested the Moon Landing/, https://www.history.com/news/apollo-11-moon-landing-launch-protests

[fn:24]https://nypost.com/2024/03/01/us-news/first-us-moon-lander-in-half-a-century-stops-working-a-week-after-tipping-over-at-touchdown/

[fn:25]Think Hank Rearden

[fn:26]Think Gail Wynand
